"""
Baseline/parity tests for the IKMC Dashboard.

These tests re-run the EXISTING, unmodified functions in
services/indicators.py and compare their output to the frozen values in
tests/baseline/baseline_snapshot.json (generated by tests/capture_baseline.py).

Purpose
-------
1. Today: guard against any accidental change to indicators.py while the
   migration work proceeds around it (refactors of loader/config/merger
   should not change a single number here).
2. Later: once FastAPI endpoints exist, a parallel test module can load the
   same baseline_snapshot.json and assert the HTTP responses match it,
   proving CURRENT STREAMLIT IMPLEMENTATION == NEW FASTAPI IMPLEMENTATION.

Nothing in this file alters business logic. A failing test here means the
computed value changed, not that the test is wrong - re-run
tests/capture_baseline.py deliberately (with justification) if the change
was intentional.
"""
import json
import math
from pathlib import Path

import pandas as pd
import pytest

BASELINE_PATH = Path(__file__).resolve().parent / "baseline" / "baseline_snapshot.json"


@pytest.fixture(scope="session")
def baseline():
    assert BASELINE_PATH.exists(), (
        f"{BASELINE_PATH} not found. Run `python tests/capture_baseline.py` "
        "once to generate it before running the parity suite."
    )
    return json.loads(BASELINE_PATH.read_text(encoding="utf-8"))


def _normalize(value):
    """Mirror the normalization capture_baseline.py applies, so a live call
    and the stored snapshot value can be compared like-for-like."""
    import numpy as np

    if isinstance(value, np.integer):
        return int(value)
    if isinstance(value, np.floating):
        return None if np.isnan(value) else float(value)
    if isinstance(value, np.bool_):
        return bool(value)
    return value


def _assert_matches(actual, expected, name):
    actual = _normalize(actual)
    if isinstance(expected, float) or isinstance(actual, float):
        if expected is None or actual is None:
            assert actual == expected, f"{name}: expected {expected!r}, got {actual!r}"
        else:
            assert math.isclose(actual, expected, rel_tol=0, abs_tol=1e-9), (
                f"{name}: expected {expected!r}, got {actual!r}"
            )
    else:
        assert actual == expected, f"{name}: expected {expected!r}, got {actual!r}"


# --------------------------------------------------------------------------
# Scalar indicators (KPI numbers, percentages, hours, counts, status strings)
# --------------------------------------------------------------------------

def test_all_baseline_scalar_functions_are_covered(indicators, baseline):
    """Tripwire: every function named in the baseline snapshot must still
    exist on services.indicators. Catches accidental renames/removals."""
    missing = [
        name for name in baseline["scalar_indicators"]
        if not hasattr(indicators, name)
    ]
    assert not missing, f"Indicator functions removed/renamed: {missing}"


@pytest.mark.parametrize(
    "func_name",
    sorted(json.loads(BASELINE_PATH.read_text(encoding="utf-8"))["scalar_indicators"].keys())
    if BASELINE_PATH.exists() else [],
)
def test_scalar_indicator_matches_baseline(func_name, indicators, baseline):
    expected = baseline["scalar_indicators"][func_name]
    fn = getattr(indicators, func_name)
    actual = fn()
    _assert_matches(actual, expected, func_name)


# --------------------------------------------------------------------------
# DataFrame-returning indicators (validation detail tables)
# --------------------------------------------------------------------------

@pytest.mark.parametrize(
    "func_name",
    sorted(json.loads(BASELINE_PATH.read_text(encoding="utf-8"))["dataframe_indicators"].keys())
    if BASELINE_PATH.exists() else [],
)
def test_dataframe_indicator_matches_baseline(func_name, indicators, baseline):
    import hashlib

    expected = baseline["dataframe_indicators"][func_name]
    fn = getattr(indicators, func_name)
    df = fn()

    assert list(df.shape) == expected["shape"], f"{func_name}: shape changed"
    assert list(df.columns) == expected["columns"], f"{func_name}: columns changed"

    normalized = df.astype(str).sort_index(axis=1)
    payload = normalized.to_csv(index=False).encode("utf-8")
    content_hash = hashlib.sha256(payload).hexdigest()
    assert content_hash == expected["content_hash"], (
        f"{func_name}: row-level content changed (hash mismatch)"
    )


# --------------------------------------------------------------------------
# Sync / freshness metadata
# --------------------------------------------------------------------------

def test_last_sync_matches_baseline(loader_module, baseline):
    expected = baseline["sync_metadata"]["get_last_sync"]
    actual = loader_module.get_last_sync()
    actual_iso = actual.isoformat() if pd.notna(actual) else None
    assert actual_iso == expected, (
        "get_last_sync() drifted from baseline. Note: despite the name, this "
        "value is NOT a data-pull timestamp - it is "
        "max(eligibility['scr_dof']), i.e. the latest screening date present "
        "in the data. See report for details."
    )


# --------------------------------------------------------------------------
# Historical hardcoded attachment values (formerly displayed by the now-
# removed Streamlit app.py, NOT computed by indicators.py)
# --------------------------------------------------------------------------

def test_real_computed_attachment_values_differ_from_hardcoded_display(indicators):
    """
    Historical: the now-removed Streamlit UI (app.py) used to display
    LITERAL hardcoded attachment-time strings on its cohort summary cards
    instead of these real computed values. That app.py comparison is gone
    along with app.py itself; this test now only confirms the indicator
    functions still return numeric attachment-hour values, preserving the
    historical hardcoded figures below as a record of what the legacy UI
    used to show for comparison.
    """
    computed_inborn_nvd = indicators.get_inborn_nvd_attachment_hours()
    computed_inborn_csection = indicators.get_inborn_csection_attachment_hours()
    computed_outborn_nvd = indicators.get_outborn_nvd_attachment_hours()
    computed_outborn_csection = indicators.get_outborn_csection_attachment_hours()

    displayed_inborn_nvd_hours = 1 + 45 / 60       # "1h 45m"
    displayed_inborn_csection_hours = 2 + 10 / 60  # "2h 10m"
    displayed_outborn_nvd_hours = 1 + 55 / 60      # "1h 55m"
    displayed_outborn_csection_hours = 3 + 45 / 60  # "3h 45m"

    # These are expected to differ today - this is informational, not a bug
    # assertion. If they ever start matching by coincidence, that's fine too.
    assert isinstance(computed_inborn_nvd, (int, float))
    assert isinstance(computed_inborn_csection, (int, float))
    assert isinstance(computed_outborn_nvd, (int, float))
    assert isinstance(computed_outborn_csection, (int, float))


# --------------------------------------------------------------------------
# Filter wiring (documents that filters currently have ZERO effect)
# --------------------------------------------------------------------------

def test_indicator_functions_accept_no_filter_arguments(indicators):
    """
    The now-removed Streamlit UI's components/filters.py used to render
    Facility/Site/From-Date/To-Date controls on every page, but that dict
    was never passed into any indicator function - none of them accept
    parameters. This test preserves that fact as a tripwire for the
    FastAPI/React port: if someone starts adding a `facility=` /
    `from_date=` parameter to an indicator function without updating the
    caller, this test will start failing and needs a conscious decision,
    not a silent partial wiring.
    """
    import inspect

    with open(BASELINE_PATH, encoding="utf-8") as f:
        baseline_data = json.load(f)

    unexpected_required_params = {}
    for func_name in baseline_data["scalar_indicators"]:
        fn = getattr(indicators, func_name, None)
        if fn is None:
            continue
        sig = inspect.signature(fn)
        required = [
            p.name for p in sig.parameters.values()
            if p.default is inspect.Parameter.empty
            and p.kind in (p.POSITIONAL_OR_KEYWORD, p.POSITIONAL_ONLY, p.KEYWORD_ONLY)
        ]
        if required:
            unexpected_required_params[func_name] = required

    assert not unexpected_required_params, (
        f"Indicator functions now require parameters (filters may be "
        f"partially wired): {unexpected_required_params}"
    )
